name: 'test my project'
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: 'ls'
      run: ls -la

    - name: 'rsa'
      run:  ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1

    - name: 'touch'
      run: touch ~/.ssh/authorized_keys
      
    - name: 'ls'
      run: ls -la
      
    - name: 'test'
      run: echo secrets.KEY >> ~/.ssh/authorized_keys
      
      

    - name: 'test2'
      run: ssh -tt -o StrictHostKeyChecking=no -vvv momai@34.123.108.90 uptime
