name: 'test my project'
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: 'ls'
      run: ls -la

    - name: 'rsa'
      #run:  ssh-keygen -q -t rsa -N '' -f /home/runner/.ssh/id_rsa <<<y >/dev/null 2>&1
      run: mkdir /home/runner/.ssh/ && touch /home/runner/.ssh/id_rsa && echo secrets.PRIVATE >>/home/runner/.ssh/id_rsa
      
    - name: 'chown'
      run: sudo chown 644 /home/runner/.ssh/id_rsa
      
    - name: 'touch'
      run: touch /home/runner/.ssh/authorized_keys
      
    - name: 'test'
      run: echo secrets.KEY >>/home/runner/.ssh/authorized_keys && sudo chown 644 /home/runner/.ssh/authorized_keys
    - name: ssh-pipeline
  # You may pin to the exact commit or the version.
  # uses: cross-the-world/ssh-pipeline@7f022867934a210af826af99ef80d96f03a094d5
      uses: cross-the-world/ssh-pipeline@v1.2.0
      with:
      # ssh remote host
        host: 34.123.108.90
    # ssh remote port
        port: 22 # optional, default is 22
    # ssh remote user
        user: momai
    # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        key: /home/runner/.ssh/authorized_keys # optional
    # connection timeout to remote host
        connect_timeout: 30 # optional, default is 30s
    # execute commands on ssh
        script: cd project/ && git pull # optional

   # - name: 'test2'
   #   run: ssh -tt -o StrictHostKeyChecking=no -vvv  momai@34.123.108.90 uptime
