name: 'test my project'
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: 'ls'
      run: ls -la

    - name: 'touch'
      run: mkdir .ssh && touch .ssh/authorized_keys
      
    - name: 'test'
      run: echo secrets.KEY >> .ssh/authorized_keys

    - name: 'test2'
      run: ssh -o StrictHostKeyChecking=no -l secrets.USENAME@34.123.108.90 'uptime'
