name: 'test my project'
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    
    - name: 'test'
      run: echo secrets.KEY

    - name: 'test2'
      run: echo .ssh/authorized_keys
      #run: ssh secrets.USENAME@34.123.108.90 'uptime'
