name: 'test my project'
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: 'rsa'
     # run:  ssh-keygen -q -t rsa -N '' -f /home/runner/.ssh/id_rsa <<<y >/dev/null 2>&1
      run: mkdir /home/runner/.ssh/ && touch /home/runner/.ssh/id_rsa && echo secrets.PRIVATE >>/home/runner/.ssh/id_rsa && sudo chown 644 /home/runner/.ssh/id_rsa
   
    - name: 'key'
      run: touch /home/runner/.ssh/id_rsa.pub &&  echo secrets.KEY >> /home/runner/.ssh/id_rsa.pub && sudo chown 644 /home/runner/.ssh/id_rsa.pub
      
    - name: 'test2'
      run: ssh -tt -o StrictHostKeyChecking=no -vvv -i momai@34.123.108.90 uptime
