name: 'test my project'
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: 'rsa'
      run:  ssh-keygen -q -t rsa -N '' -f /home/runner/.ssh/id_rsa <<<y >/dev/null 2>&1 && ssh-keygen -p -m PEM -N '' -f /home/runner/.ssh/id_rsa
   
    - name: 'key'
      run: touch /home/runner/.ssh/authorized_keys &&  echo secrets.KEY >>/home/runner/.ssh/authorized_keys && sudo chown 644 /home/runner/.ssh/authorized_keys
      
    - name: 'test2'
      run: ssh -tt -o StrictHostKeyChecking=no -vvv -i /home/runner/.ssh/authorized_keys  momai@34.123.108.90 uptime
