name: 'update web pages'
on:
  push:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: 'add key'
      env:
       SECRETS_KEY: ${{ secrets.KEY }}
      run: sudo echo $SECRETS_KEY >> ~/.ssh/id_rsa.pub

    - name: 'run script backupbd'
      env:
       SECRETS_USERNAME: ${{ secrets.USERNAME }}
       SECRETS_HOST: ${{ secrets.HOST }}
      run: ssh $SECRETS_USERNAME@$SECRETS_HOST sh nginx-phpfpm-mysql-phpmyadmin/backupbd.sh

    - name: 'run script git pull'
      env:
       SECRETS_USERNAME: ${{ secrets.USERNAME }}
       SECRETS_HOST: ${{ secrets.HOST }}
      run: $SECRETS_USERNAME@$SECRETS_HOST sh nginx-phpfpm-mysql-phpmyadmin/update.sh
