name: 'test my project'
on:
  push:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: 'add key'
      env:
       SECRETS_KEY: ${{ secrets.KEY }}
      run: sudo echo $SECRETS_KEY >> ~/.ssh/id_rsa.pub

    - name: 'run script git pull'
      run: ssh momai@34.123.108.90 sh project/restart.sh
